meta_product_name: "Super 8"
meta_title: "Super 8 - Des films à voir avec ses enfants"
meta_description: "Une selection par âges et par thèmes pour partager une culture cinématographique avec ses enfants "
meta_image: "logo.svg"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@MovSuper8"
